import { MD3LightTheme as DefaultTheme, MD3Theme } from "react-native-paper";

export const theme: MD3Theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: "#173e74",
  },
  fonts: {
    ...DefaultTheme.fonts,
    displayLarge: {
      fontFamily: "Roboto_400Regular",
      fontWeight: "400",
      fontSize: 57,
      lineHeight: 64,
      letterSpacing: -0.25,
    },
    displayMedium: {
      fontFamily: "Roboto_400Regular",
      fontWeight: "400",
      fontSize: 45,
      lineHeight: 52,
      letterSpacing: 0,
    },
    displaySmall: {
      fontFamily: "Roboto_400Regular",
      fontWeight: "400",
      fontSize: 36,
      lineHeight: 44,
      letterSpacing: 0,
    },
    headlineLarge: {
      fontFamily: "Roboto_400Regular",
      fontWeight: "400",
      fontSize: 32,
      lineHeight: 40,
      letterSpacing: 0,
    },
    headlineMedium: {
      fontFamily: "Roboto_400Regular",
      fontWeight: "400",
      fontSize: 28,
      lineHeight: 36,
      letterSpacing: 0,
    },
    headlineSmall: {
      fontFamily: "Roboto_400Regular",
      fontWeight: "400",
      fontSize: 24,
      lineHeight: 32,
      letterSpacing: 0,
    },
    titleLarge: {
      fontFamily: "Roboto_400Regular",
      fontWeight: "400",
      fontSize: 22,
      lineHeight: 28,
      letterSpacing: 0,
    },
    titleMedium: {
      fontFamily: "Roboto_500Medium",
      fontWeight: "500",
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.15,
    },
    titleSmall: {
      fontFamily: "Roboto_500Medium",
      fontWeight: "500",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    labelLarge: {
      fontFamily: "Roboto_500Medium",
      fontWeight: "500",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    labelMedium: {
      fontFamily: "Roboto_500Medium",
      fontWeight: "500",
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    labelSmall: {
      fontFamily: "Roboto_500Medium",
      fontWeight: "500",
      fontSize: 11,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    bodyLarge: {
      fontFamily: "Roboto_400Regular",
      fontWeight: "400",
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.5,
    },
    bodyMedium: {
      fontFamily: "Roboto_400Regular",
      fontWeight: "400",
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.25,
    },
    bodySmall: {
      fontFamily: "Roboto_400Regular",
      fontWeight: "400",
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.4,
    },
  },
};
